version: 2
jobs:
  build:
    docker:
      - image: icepack/firedrake:buster
    working_directory: ~/icepack
    steps:
      - checkout
      - run: pip3 install --editable .
      - run: pytest --capture=no --verbose
